[[cors]]
allowed_origins = "*"
allowed_methods = ["GET", "POST"]
allowed_headers = "*"

[[headers]]
for = ["**/*.woff2", "**/*.woff", "**/*.svg", "**/*.ttf", "**/*.otf", "**/*.eot", "**/*.js", "**/*.css"]
compress = "gzip"
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[headers]]
for = ["**/*.png", "**/*.jpg", "**/*.jpeg", "**/*.gif", "**/*.webp"]
[headers.values]
Cache-Control = "max-age=31536000, no-transform, public"

[[redirects]]
from = "/agenda/2024-03-17-salon-du-val-de-cher/"
to = "/expositions/2023/salon-du-val-de-cher/"

[[redirects]]
from = "/oeuvres/2021-coquine/"
to = "/oeuvres/2005-coquine/"

[[redirects]]
from = "/oeuvres/2023-rythmes/"
to = "/oeuvres/1997-rythmes/"

[[redirects]]
from = "/oeuvres/2023-la-natte/"
to = "/oeuvres/2008-la-natte/"

[[redirects]]
from = "/oeuvres/2021-vrille/"
to = "/oeuvres/2012-vrille/"

[[redirects]]
from = "/projets/"
to = "/oeuvres/"

[[redirects]]
from = "/oeuvres/2023-la-boucle-d-oreille/"
to = "/oeuvres/1998-la-boucle-d-oreille/"

[[redirects]]
from = "/oeuvres/2023-le-bonbon/"
to = "/oeuvres/2011-le-bonbon/"

[[redirects]]
from = "/oeuvres/2022-coquette/"
to = "/oeuvres/2014-coquette/"

[[redirects]]
from = "/oeuvres/2023-youpi/"
to = "/oeuvres/2009-youpi/"

[[redirects]]
from = "/oeuvres/2022-la-recre/"
to = "/oeuvres/2008-la-recre/"

[[redirects]]
from = "/oeuvres/2023-youpi-envolee/"
to = "/oeuvres/2009-youpi-envolee/"

[[redirects]]
from = "/oeuvres/2019-gestation/"
to = "/oeuvres/2010-gestation/"

[[redirects]]
from = "/oeuvres/2023-grain-de-sable/"
to = "/oeuvres/2001-grain-de-sable/"

[[redirects]]
from = "/oeuvres/2023-fou-rire/"
to = "/oeuvres/2005-fou-rire/"

[[redirects]]
from = "/oeuvres/2023-clair-de-lune/"
to = "/oeuvres/2001-clair-de-lune/"

[[redirects]]
from = "/oeuvres/2020-pudique/"
to = "/oeuvres/2011-pudique/"

[[redirects]]
from = "/expositions/2023-03-26-salon-du-val-de-cher/"
to = "/expositions/2023/salon-du-val-de-cher/"

[[redirects]]
from = "/lartiste/"
to = "/a-propos/"

[[redirects]]
from = "/oeuvres/2021-sarah/"
to = "/oeuvres/2013-sarah/"

[[redirects]]
from = "/agenda/archives/"
to = "/expositions/archives/"

[[redirects]]
from = "/equipe-editoriale/"
to = "/equipe/equipe-editoriale/"

[[redirects]]
from = "/oeuvres/2019-tango/"
to = "/oeuvres/2007-tango/"

[[redirects]]
from = "/oeuvres/2019-feline/"
to = "/oeuvres/2009-feline/"

[[redirects]]
from = "/agenda/2023-03-26-salon-du-val-de-cher/"
to = "/expositions/2023/salon-du-val-de-cher/"

[[redirects]]
from = "/oeuvres/2023-dammarie/"
to = "/oeuvres/1999-dammarie/"

[[redirects]]
from = "/oeuvres/2023-petit-malin/"
to = "/oeuvres/2005-petit-malin/"

[[redirects]]
from = "/oeuvres/2023-plenitude/"
to = "/oeuvres/2010-plenitude/"

[[redirects]]
from = "/oeuvres/2023-a-venir/"
to = "/oeuvres/2006-a-venir/"

[[redirects]]
from = "/oeuvres/2023-reves/"
to = "/oeuvres/2004-reves/"

[[redirects]]
from = "/oeuvres/2023-la-source/"
to = "/oeuvres/2008-la-source/"

[[redirects]]
from = "/oeuvres/2023-le-mur/"
to = "/oeuvres/1989-le-mur/"

[[redirects]]
from = "/agenda/"
to = "/expositions/"

[[redirects]]
from = "/projets/2022-lea/"
to = "/oeuvres/2022-lea/"

[[redirects]]
from = "/oeuvres/2023-prima-calza/"
to = "/oeuvres/1999-prima-calza/"

[[redirects]]
from = "/oeuvres/2023-buste-mathieu/"
to = "/oeuvres/2007-buste-mathieu/"

[[redirects]]
from = "/oeuvres/2023-maree-basse/"
to = "/oeuvres/2002-maree-basse/"

[[redirects]]
from = "/oeuvres/2023-nonna/"
to = "/oeuvres/1990-nonna/"

[[redirects]]
from = "/oeuvres/2023-le-lien/"
to = "/oeuvres/2004-le-lien/"

[[redirects]]
from = "/oeuvres/2023-onde/"
to = "/oeuvres/2000-onde/"

[[redirects]]
from = "/oeuvres/2019-la-vague/"
to = "/oeuvres/2000-la-vague/"

[[redirects]]
from = "/oeuvres/2023-aurore/"
to = "/oeuvres/2002-aurore/"

[[redirects]]
from = "/publications/"
to = "/actualites/"

[[redirects]]
from = "/oeuvres/2022-fanny/"
to = "/oeuvres/2015-fanny/"

[[redirects]]
from = "/oeuvres/2023-cabaret/"
to = "/oeuvres/2005-cabaret/"

[[redirects]]
from = "/oeuvres/2023-jeux/"
to = "/oeuvres/1998-jeux/"

[[redirects]]
from = "/oeuvres/2023-elles/"
to = "/oeuvres/2000-elles/"

[[redirects]]
from = "/oeuvres/2020-mutande/"
to = "/oeuvres/2004-mutanda/"

[[redirects]]
from = "/oeuvres/2023-jeu-d-eau/"
to = "/oeuvres/2005-jeu-d-eau/"

